# Generated by Django 2.0.5 on 2018-07-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
