# Generated by Django 2.0.5 on 2018-07-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creates',
            new_name='Create',
        ),
        migrations.RenameModel(
            old_name='Hires',
            new_name='Hire',
        ),
        migrations.RenameModel(
            old_name='Licenses',
            new_name='License',
        ),
    ]
