# Generated by Django 2.0.7 on 2018-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.IntegerField(choices=[(0, 'Mystery'), (1, 'Drama'), (2, 'SciFi'), (3, 'Action'), (4, 'Fantasy'), (5, 'Comedy'), (6, 'Mecha')]),
        ),
    ]
